apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ${APP_NAMESPACE}
  labels:
    version: v1
    app: rpc-user
    app.kubernetes.io/version: v1
    app.kubernetes.io/name: rpc-user
  name: rpc-user-v1
  annotations:
    servicemesh.kubesphere.io/enabled: 'true'
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      version: v1
      app: rpc-user
      app.kubernetes.io/version: v1
      app.kubernetes.io/name: rpc-user
  template:
    metadata:
      labels:
        version: v1
        app: rpc-user
        app.kubernetes.io/version: v1
        app.kubernetes.io/name: rpc-user
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - name: rpc-user
          imagePullPolicy: Always
          image: ${IMAGE}
          ports:
            - name: grpc-user
              protocol: TCP
              containerPort: 8080
          env:
            - name: ENV
              value: ${ENV_NAME}
      serviceAccount: default
      affinity: {}
      initContainers: []
      volumes: []
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
apiVersion: v1
kind: Service
metadata:
  namespace: ${APP_NAMESPACE}
  labels:
    version: v1
    app: rpc-user
    app.kubernetes.io/version: v1
    app.kubernetes.io/name: rpc-user
  annotations:
    kubesphere.io/serviceType: statelessservice
    servicemesh.kubesphere.io/enabled: 'true'
  name: rpc-user
spec:
  sessionAffinity: None
  selector:
    app: rpc-user
    app.kubernetes.io/version: v1
    app.kubernetes.io/name: rpc-user
  ports:
    - name: grpc-user
      protocol: TCP
      port: 8080
      targetPort: 8080
