services:
  rpc-user:
    build:
      context: .
      dockerfile: Dockerfile
    image: rpc-user:latest
    container_name: rpc-user
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./etc:/app/etc
    environment:
      - ETCD_ENDPOINTS=10.8.0.1:2379
    networks:
      - thinktalk-net

networks:
  thinktalk-net:
    driver: bridge
