// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package user

import (
	"context"

	"rpc-user/user/service"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdminUserItem           = service.AdminUserItem
	AdminUserListRequest    = service.AdminUserListRequest
	AdminUserListResponse   = service.AdminUserListResponse
	FindByIdRequest         = service.FindByIdRequest
	FindByIdResponse        = service.FindByIdResponse
	FindByMobileRequest     = service.FindByMobileRequest
	FindByMobileResponse    = service.FindByMobileResponse
	RegisterRequest         = service.RegisterRequest
	RegisterResponse        = service.RegisterResponse
	SendSmsRequest          = service.SendSmsRequest
	SendSmsResponse         = service.SendSmsResponse
	UpdateProfileRequest    = service.UpdateProfileRequest
	UpdateProfileResponse   = service.UpdateProfileResponse
	UpgradePasswordRequest  = service.UpgradePasswordRequest
	UpgradePasswordResponse = service.UpgradePasswordResponse

	User interface {
		Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
		FindById(ctx context.Context, in *FindByIdRequest, opts ...grpc.CallOption) (*FindByIdResponse, error)
		FindByMobile(ctx context.Context, in *FindByMobileRequest, opts ...grpc.CallOption) (*FindByMobileResponse, error)
		SendSms(ctx context.Context, in *SendSmsRequest, opts ...grpc.CallOption) (*SendSmsResponse, error)
		UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error)
		UpgradePassword(ctx context.Context, in *UpgradePasswordRequest, opts ...grpc.CallOption) (*UpgradePasswordResponse, error)
		AdminUserList(ctx context.Context, in *AdminUserListRequest, opts ...grpc.CallOption) (*AdminUserListResponse, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	client := service.NewUserClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultUser) FindById(ctx context.Context, in *FindByIdRequest, opts ...grpc.CallOption) (*FindByIdResponse, error) {
	client := service.NewUserClient(m.cli.Conn())
	return client.FindById(ctx, in, opts...)
}

func (m *defaultUser) FindByMobile(ctx context.Context, in *FindByMobileRequest, opts ...grpc.CallOption) (*FindByMobileResponse, error) {
	client := service.NewUserClient(m.cli.Conn())
	return client.FindByMobile(ctx, in, opts...)
}

func (m *defaultUser) SendSms(ctx context.Context, in *SendSmsRequest, opts ...grpc.CallOption) (*SendSmsResponse, error) {
	client := service.NewUserClient(m.cli.Conn())
	return client.SendSms(ctx, in, opts...)
}

func (m *defaultUser) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error) {
	client := service.NewUserClient(m.cli.Conn())
	return client.UpdateProfile(ctx, in, opts...)
}

func (m *defaultUser) UpgradePassword(ctx context.Context, in *UpgradePasswordRequest, opts ...grpc.CallOption) (*UpgradePasswordResponse, error) {
	client := service.NewUserClient(m.cli.Conn())
	return client.UpgradePassword(ctx, in, opts...)
}

func (m *defaultUser) AdminUserList(ctx context.Context, in *AdminUserListRequest, opts ...grpc.CallOption) (*AdminUserListResponse, error) {
	client := service.NewUserClient(m.cli.Conn())
	return client.AdminUserList(ctx, in, opts...)
}
