// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package user

import (
	"context"

	"rpc-user/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdminUserListRequest    = user.AdminUserListRequest
	AdminUserListResponse   = user.AdminUserListResponse
	FindByIdRequest         = user.FindByIdRequest
	FindByIdResponse        = user.FindByIdResponse
	FindByMobileRequest     = user.FindByMobileRequest
	FindByMobileResponse    = user.FindByMobileResponse
	RegisterRequest         = user.RegisterRequest
	RegisterResponse        = user.RegisterResponse
	SendSmsRequest          = user.SendSmsRequest
	SendSmsResponse         = user.SendSmsResponse
	UpdateProfileRequest    = user.UpdateProfileRequest
	UpdateProfileResponse   = user.UpdateProfileResponse
	UpgradePasswordRequest  = user.UpgradePasswordRequest
	UpgradePasswordResponse = user.UpgradePasswordResponse

	User interface {
		Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
		FindById(ctx context.Context, in *FindByIdRequest, opts ...grpc.CallOption) (*FindByIdResponse, error)
		FindByMobile(ctx context.Context, in *FindByMobileRequest, opts ...grpc.CallOption) (*FindByMobileResponse, error)
		SendSms(ctx context.Context, in *SendSmsRequest, opts ...grpc.CallOption) (*SendSmsResponse, error)
		UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error)
		UpgradePassword(ctx context.Context, in *UpgradePasswordRequest, opts ...grpc.CallOption) (*UpgradePasswordResponse, error)
		AdminUserList(ctx context.Context, in *AdminUserListRequest, opts ...grpc.CallOption) (*AdminUserListResponse, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultUser) FindById(ctx context.Context, in *FindByIdRequest, opts ...grpc.CallOption) (*FindByIdResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.FindById(ctx, in, opts...)
}

func (m *defaultUser) FindByMobile(ctx context.Context, in *FindByMobileRequest, opts ...grpc.CallOption) (*FindByMobileResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.FindByMobile(ctx, in, opts...)
}

func (m *defaultUser) SendSms(ctx context.Context, in *SendSmsRequest, opts ...grpc.CallOption) (*SendSmsResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.SendSms(ctx, in, opts...)
}

func (m *defaultUser) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdateProfile(ctx, in, opts...)
}

func (m *defaultUser) UpgradePassword(ctx context.Context, in *UpgradePasswordRequest, opts ...grpc.CallOption) (*UpgradePasswordResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpgradePassword(ctx, in, opts...)
}

func (m *defaultUser) AdminUserList(ctx context.Context, in *AdminUserListRequest, opts ...grpc.CallOption) (*AdminUserListResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.AdminUserList(ctx, in, opts...)
}
