// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package server

import (
	"context"

	"rpc-user/internal/logic/follow"
	"rpc-user/internal/svc"
	"rpc-user/user"
)

type FollowServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedFollowServer
}

func NewFollowServer(svcCtx *svc.ServiceContext) *FollowServer {
	return &FollowServer{
		svcCtx: svcCtx,
	}
}

func (s *FollowServer) Follow(ctx context.Context, in *user.FollowRequest) (*user.FollowResponse, error) {
	l := followlogic.NewFollowLogic(ctx, s.svcCtx)
	return l.Follow(in)
}

func (s *FollowServer) UnFollow(ctx context.Context, in *user.UnFollowRequest) (*user.UnFollowResponse, error) {
	l := followlogic.NewUnFollowLogic(ctx, s.svcCtx)
	return l.UnFollow(in)
}

func (s *FollowServer) FollowList(ctx context.Context, in *user.FollowListRequest) (*user.FollowListResponse, error) {
	l := followlogic.NewFollowListLogic(ctx, s.svcCtx)
	return l.FollowList(in)
}

func (s *FollowServer) FansList(ctx context.Context, in *user.FansListRequest) (*user.FansListResponse, error) {
	l := followlogic.NewFansListLogic(ctx, s.svcCtx)
	return l.FansList(in)
}
