// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package server

import (
	"context"

	"rpc-user/user/internal/logic"
	"rpc-user/user/internal/svc"
	"rpc-user/user/service"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	service.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Register(ctx context.Context, in *service.RegisterRequest) (*service.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) FindById(ctx context.Context, in *service.FindByIdRequest) (*service.FindByIdResponse, error) {
	l := logic.NewFindByIdLogic(ctx, s.svcCtx)
	return l.FindById(in)
}

func (s *UserServer) FindByMobile(ctx context.Context, in *service.FindByMobileRequest) (*service.FindByMobileResponse, error) {
	l := logic.NewFindByMobileLogic(ctx, s.svcCtx)
	return l.FindByMobile(in)
}

func (s *UserServer) SendSms(ctx context.Context, in *service.SendSmsRequest) (*service.SendSmsResponse, error) {
	l := logic.NewSendSmsLogic(ctx, s.svcCtx)
	return l.SendSms(in)
}

func (s *UserServer) UpdateProfile(ctx context.Context, in *service.UpdateProfileRequest) (*service.UpdateProfileResponse, error) {
	l := logic.NewUpdateProfileLogic(ctx, s.svcCtx)
	return l.UpdateProfile(in)
}

func (s *UserServer) UpgradePassword(ctx context.Context, in *service.UpgradePasswordRequest) (*service.UpgradePasswordResponse, error) {
	l := logic.NewUpgradePasswordLogic(ctx, s.svcCtx)
	return l.UpgradePassword(in)
}

func (s *UserServer) AdminUserList(ctx context.Context, in *service.AdminUserListRequest) (*service.AdminUserListResponse, error) {
	l := logic.NewAdminUserListLogic(ctx, s.svcCtx)
	return l.AdminUserList(in)
}
