syntax = "proto3";

package user;
option go_package = "api-thinktalk/client/follow/pb;pb";

service Follow {
  rpc Follow(FollowRequest) returns (FollowResponse);
  rpc UnFollow(UnFollowRequest) returns (UnFollowResponse);
  rpc FollowList(FollowListRequest) returns (FollowListResponse);
  rpc FansList(FansListRequest) returns (FansListResponse);
}

message FollowRequest {
  int64 userId = 1;
  int64 followedUserId = 2;
}

message FollowResponse {
  int64 code = 1;
  string msg = 2;
}

message UnFollowRequest {
  int64 userId = 1;
  int64 followedUserId = 2;
}

message UnFollowResponse {
  int64 code = 1;
  string msg = 2;
}

message FollowListRequest {
  int64 id = 1;
  int64 userId = 2;
  int64 cursor = 3;
  int64 pageSize = 4;
}

message FollowItem {
  int64 id = 1;
  int64 followedUserId = 2;
  int64 fansCount = 3;
  int64 createTime = 4;
}

message FollowListData {
  repeated FollowItem items = 1;
  int64 cursor = 2;
  bool isEnd = 3;
  int64 id = 4;
}

message FollowListResponse {
  int64 code = 1;
  string msg = 2;
  FollowListData data = 3;
}

message FansListRequest {
  int64 id = 1;
  int64 userId = 2;
  int64 cursor = 3;
  int64 pageSize = 4;
}

message FansItem {
  int64 id = 1;
  int64 userId = 2;
  int64 fansUserId = 3;
  int64 followCount = 4;
  int64 fansCount = 5;
  int64 createTime = 6;
}

message FansListData {
  repeated FansItem items = 1;
  int64 cursor = 2;
  bool isEnd = 3;
  int64 id = 4;
}

message FansListResponse {
  int64 code = 1;
  string msg = 2;
  FansListData data = 3;
}