syntax = "proto3";

package user;
option go_package = "api-thinktalk/client/user/service;service";

service User {
  rpc Register(RegisterRequest) returns (RegisterResponse);
  rpc FindById(FindByIdRequest) returns (FindByIdResponse);
  rpc FindByMobile(FindByMobileRequest) returns (FindByMobileResponse);
  rpc SendSms(SendSmsRequest) returns (SendSmsResponse);
  rpc UpdateProfile(UpdateProfileRequest) returns (UpdateProfileResponse);
  rpc UpgradePassword(UpgradePasswordRequest) returns (UpgradePasswordResponse);
  rpc AdminUserList(AdminUserListRequest) returns (AdminUserListResponse);
}

message RegisterRequest {
  string username = 1;
  string mobile = 2;
  string avatar = 3;
  string password = 4;
}

message RegisterData {
  int64 userId = 1;
}

message RegisterResponse {
  int64 code = 1;
  string msg = 2;
  RegisterData data = 3;
}

message FindByIdRequest {
  int64 userId = 1;
}

message UserInfoData {
  int64 userId = 1;
  string username = 2;
  string mobile = 3;
  string avatar = 4;
  int64 role = 5;
  string displayId = 6;
  string bio = 7;
  int32 gender = 8;
  string profileCover = 9;
}

message FindByIdResponse {
  int64 code = 1;
  string msg = 2;
  UserInfoData data = 3;
}

message FindByMobileRequest {
  string mobile = 1;
}

message UserAuthData {
  int64 userId = 1;
  string username = 2;
  string mobile = 3;
  string avatar = 4;
  string password = 5;
  int64 role = 6;
}

message FindByMobileResponse {
  int64 code = 1;
  string msg = 2;
  UserAuthData data = 3;
}

message SendSmsRequest {
  int64 userId = 1;
  string mobile = 2;
}

message SendSmsResponse {
  int64 code = 1;
  string msg = 2;
}

message UpdateProfileRequest {
  int64 userId = 1;
  string username = 2;
  string avatar = 3;
  string bio = 4;
  int32 gender = 5;
  string profileCover = 6;
}

message UpdateProfileResponse {
  int64 code = 1;
  string msg = 2;
}

message UpgradePasswordRequest {
  int64 userId = 1;
  string passwordHash = 2;
}

message UpgradePasswordResponse {
  int64 code = 1;
  string msg = 2;
}

message AdminUserListRequest {
  string keyword = 1;
  int64 cursor = 2;
  int64 pageSize = 3;
}

message AdminUserListData {
  repeated UserInfoData users = 1;
  int64 cursor = 2;
  bool isEnd = 3;
}

message AdminUserListResponse {
  int64 code = 1;
  string msg = 2;
  AdminUserListData data = 3;
}