// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: member.proto

package server

import (
	"context"

	"rpc-user/member/internal/logic"
	"rpc-user/member/internal/svc"
	"rpc-user/member/pb"
)

type MemberServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedMemberServer
}

func NewMemberServer(svcCtx *svc.ServiceContext) *MemberServer {
	return &MemberServer{
		svcCtx: svcCtx,
	}
}

func (s *MemberServer) MemberInfo(ctx context.Context, in *pb.MemberInfoRequest) (*pb.MemberInfoResponse, error) {
	l := logic.NewMemberInfoLogic(ctx, s.svcCtx)
	return l.MemberInfo(in)
}

func (s *MemberServer) UpgradeMember(ctx context.Context, in *pb.UpgradeMemberRequest) (*pb.UpgradeMemberResponse, error) {
	l := logic.NewUpgradeMemberLogic(ctx, s.svcCtx)
	return l.UpgradeMember(in)
}

func (s *MemberServer) CheckMemberRight(ctx context.Context, in *pb.CheckMemberRightRequest) (*pb.CheckMemberRightResponse, error) {
	l := logic.NewCheckMemberRightLogic(ctx, s.svcCtx)
	return l.CheckMemberRight(in)
}

func (s *MemberServer) MemberOrderList(ctx context.Context, in *pb.MemberOrderListRequest) (*pb.MemberOrderListResponse, error) {
	l := logic.NewMemberOrderListLogic(ctx, s.svcCtx)
	return l.MemberOrderList(in)
}

func (s *MemberServer) CreateOrder(ctx context.Context, in *pb.CreateOrderRequest) (*pb.CreateOrderResponse, error) {
	l := logic.NewCreateOrderLogic(ctx, s.svcCtx)
	return l.CreateOrder(in)
}

func (s *MemberServer) PayCallback(ctx context.Context, in *pb.PayCallbackRequest) (*pb.PayCallbackResponse, error) {
	l := logic.NewPayCallbackLogic(ctx, s.svcCtx)
	return l.PayCallback(in)
}
