// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: member.proto

package member

import (
	"context"

	"rpc-user/member/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CheckMemberRightRequest  = pb.CheckMemberRightRequest
	CheckMemberRightResponse = pb.CheckMemberRightResponse
	CreateOrderRequest       = pb.CreateOrderRequest
	CreateOrderResponse      = pb.CreateOrderResponse
	MemberInfoRequest        = pb.MemberInfoRequest
	MemberInfoResponse       = pb.MemberInfoResponse
	MemberOrderItem          = pb.MemberOrderItem
	MemberOrderListRequest   = pb.MemberOrderListRequest
	MemberOrderListResponse  = pb.MemberOrderListResponse
	PayCallbackRequest       = pb.PayCallbackRequest
	PayCallbackResponse      = pb.PayCallbackResponse
	UpgradeMemberRequest     = pb.UpgradeMemberRequest
	UpgradeMemberResponse    = pb.UpgradeMemberResponse

	Member interface {
		MemberInfo(ctx context.Context, in *MemberInfoRequest, opts ...grpc.CallOption) (*MemberInfoResponse, error)
		UpgradeMember(ctx context.Context, in *UpgradeMemberRequest, opts ...grpc.CallOption) (*UpgradeMemberResponse, error)
		CheckMemberRight(ctx context.Context, in *CheckMemberRightRequest, opts ...grpc.CallOption) (*CheckMemberRightResponse, error)
		MemberOrderList(ctx context.Context, in *MemberOrderListRequest, opts ...grpc.CallOption) (*MemberOrderListResponse, error)
		CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
		PayCallback(ctx context.Context, in *PayCallbackRequest, opts ...grpc.CallOption) (*PayCallbackResponse, error)
	}

	defaultMember struct {
		cli zrpc.Client
	}
)

func NewMember(cli zrpc.Client) Member {
	return &defaultMember{
		cli: cli,
	}
}

func (m *defaultMember) MemberInfo(ctx context.Context, in *MemberInfoRequest, opts ...grpc.CallOption) (*MemberInfoResponse, error) {
	client := pb.NewMemberClient(m.cli.Conn())
	return client.MemberInfo(ctx, in, opts...)
}

func (m *defaultMember) UpgradeMember(ctx context.Context, in *UpgradeMemberRequest, opts ...grpc.CallOption) (*UpgradeMemberResponse, error) {
	client := pb.NewMemberClient(m.cli.Conn())
	return client.UpgradeMember(ctx, in, opts...)
}

func (m *defaultMember) CheckMemberRight(ctx context.Context, in *CheckMemberRightRequest, opts ...grpc.CallOption) (*CheckMemberRightResponse, error) {
	client := pb.NewMemberClient(m.cli.Conn())
	return client.CheckMemberRight(ctx, in, opts...)
}

func (m *defaultMember) MemberOrderList(ctx context.Context, in *MemberOrderListRequest, opts ...grpc.CallOption) (*MemberOrderListResponse, error) {
	client := pb.NewMemberClient(m.cli.Conn())
	return client.MemberOrderList(ctx, in, opts...)
}

func (m *defaultMember) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	client := pb.NewMemberClient(m.cli.Conn())
	return client.CreateOrder(ctx, in, opts...)
}

func (m *defaultMember) PayCallback(ctx context.Context, in *PayCallbackRequest, opts ...grpc.CallOption) (*PayCallbackResponse, error) {
	client := pb.NewMemberClient(m.cli.Conn())
	return client.PayCallback(ctx, in, opts...)
}
