// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package member

import (
	"context"

	"rpc-user/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CheckMemberRightRequest  = user.CheckMemberRightRequest
	CheckMemberRightResponse = user.CheckMemberRightResponse
	CreateOrderRequest       = user.CreateOrderRequest
	CreateOrderResponse      = user.CreateOrderResponse
	MemberInfoRequest        = user.MemberInfoRequest
	MemberInfoResponse       = user.MemberInfoResponse
	MemberOrderListRequest   = user.MemberOrderListRequest
	MemberOrderListResponse  = user.MemberOrderListResponse
	PayCallbackRequest       = user.PayCallbackRequest
	PayCallbackResponse      = user.PayCallbackResponse
	UpgradeMemberRequest     = user.UpgradeMemberRequest
	UpgradeMemberResponse    = user.UpgradeMemberResponse

	Member interface {
		MemberInfo(ctx context.Context, in *MemberInfoRequest, opts ...grpc.CallOption) (*MemberInfoResponse, error)
		UpgradeMember(ctx context.Context, in *UpgradeMemberRequest, opts ...grpc.CallOption) (*UpgradeMemberResponse, error)
		CheckMemberRight(ctx context.Context, in *CheckMemberRightRequest, opts ...grpc.CallOption) (*CheckMemberRightResponse, error)
		MemberOrderList(ctx context.Context, in *MemberOrderListRequest, opts ...grpc.CallOption) (*MemberOrderListResponse, error)
		CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
		PayCallback(ctx context.Context, in *PayCallbackRequest, opts ...grpc.CallOption) (*PayCallbackResponse, error)
	}

	defaultMember struct {
		cli zrpc.Client
	}
)

func NewMember(cli zrpc.Client) Member {
	return &defaultMember{
		cli: cli,
	}
}

func (m *defaultMember) MemberInfo(ctx context.Context, in *MemberInfoRequest, opts ...grpc.CallOption) (*MemberInfoResponse, error) {
	client := user.NewMemberClient(m.cli.Conn())
	return client.MemberInfo(ctx, in, opts...)
}

func (m *defaultMember) UpgradeMember(ctx context.Context, in *UpgradeMemberRequest, opts ...grpc.CallOption) (*UpgradeMemberResponse, error) {
	client := user.NewMemberClient(m.cli.Conn())
	return client.UpgradeMember(ctx, in, opts...)
}

func (m *defaultMember) CheckMemberRight(ctx context.Context, in *CheckMemberRightRequest, opts ...grpc.CallOption) (*CheckMemberRightResponse, error) {
	client := user.NewMemberClient(m.cli.Conn())
	return client.CheckMemberRight(ctx, in, opts...)
}

func (m *defaultMember) MemberOrderList(ctx context.Context, in *MemberOrderListRequest, opts ...grpc.CallOption) (*MemberOrderListResponse, error) {
	client := user.NewMemberClient(m.cli.Conn())
	return client.MemberOrderList(ctx, in, opts...)
}

func (m *defaultMember) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	client := user.NewMemberClient(m.cli.Conn())
	return client.CreateOrder(ctx, in, opts...)
}

func (m *defaultMember) PayCallback(ctx context.Context, in *PayCallbackRequest, opts ...grpc.CallOption) (*PayCallbackResponse, error) {
	client := user.NewMemberClient(m.cli.Conn())
	return client.PayCallback(ctx, in, opts...)
}
