// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package server

import (
	"context"

	"rpc-user/internal/logic/member"
	"rpc-user/internal/svc"
	"rpc-user/user"
)

type MemberServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedMemberServer
}

func NewMemberServer(svcCtx *svc.ServiceContext) *MemberServer {
	return &MemberServer{
		svcCtx: svcCtx,
	}
}

func (s *MemberServer) MemberInfo(ctx context.Context, in *user.MemberInfoRequest) (*user.MemberInfoResponse, error) {
	l := memberlogic.NewMemberInfoLogic(ctx, s.svcCtx)
	return l.MemberInfo(in)
}

func (s *MemberServer) UpgradeMember(ctx context.Context, in *user.UpgradeMemberRequest) (*user.UpgradeMemberResponse, error) {
	l := memberlogic.NewUpgradeMemberLogic(ctx, s.svcCtx)
	return l.UpgradeMember(in)
}

func (s *MemberServer) CheckMemberRight(ctx context.Context, in *user.CheckMemberRightRequest) (*user.CheckMemberRightResponse, error) {
	l := memberlogic.NewCheckMemberRightLogic(ctx, s.svcCtx)
	return l.CheckMemberRight(in)
}

func (s *MemberServer) MemberOrderList(ctx context.Context, in *user.MemberOrderListRequest) (*user.MemberOrderListResponse, error) {
	l := memberlogic.NewMemberOrderListLogic(ctx, s.svcCtx)
	return l.MemberOrderList(in)
}

func (s *MemberServer) CreateOrder(ctx context.Context, in *user.CreateOrderRequest) (*user.CreateOrderResponse, error) {
	l := memberlogic.NewCreateOrderLogic(ctx, s.svcCtx)
	return l.CreateOrder(in)
}

func (s *MemberServer) PayCallback(ctx context.Context, in *user.PayCallbackRequest) (*user.PayCallbackResponse, error) {
	l := memberlogic.NewPayCallbackLogic(ctx, s.svcCtx)
	return l.PayCallback(in)
}
