// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: member.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MemberInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberInfoRequest) Reset() {
	*x = MemberInfoRequest{}
	mi := &file_member_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberInfoRequest) ProtoMessage() {}

func (x *MemberInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberInfoRequest.ProtoReflect.Descriptor instead.
func (*MemberInfoRequest) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{0}
}

func (x *MemberInfoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type MemberInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	LevelName     string                 `protobuf:"bytes,3,opt,name=levelName,proto3" json:"levelName,omitempty"`
	ExpireTime    int64                  `protobuf:"varint,4,opt,name=expireTime,proto3" json:"expireTime,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberInfoResponse) Reset() {
	*x = MemberInfoResponse{}
	mi := &file_member_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberInfoResponse) ProtoMessage() {}

func (x *MemberInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberInfoResponse.ProtoReflect.Descriptor instead.
func (*MemberInfoResponse) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{1}
}

func (x *MemberInfoResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MemberInfoResponse) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *MemberInfoResponse) GetLevelName() string {
	if x != nil {
		return x.LevelName
	}
	return ""
}

func (x *MemberInfoResponse) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *MemberInfoResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpgradeMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	DurationDays  int32                  `protobuf:"varint,3,opt,name=durationDays,proto3" json:"durationDays,omitempty"`
	TransactionId string                 `protobuf:"bytes,4,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	PayChannel    string                 `protobuf:"bytes,6,opt,name=payChannel,proto3" json:"payChannel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeMemberRequest) Reset() {
	*x = UpgradeMemberRequest{}
	mi := &file_member_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeMemberRequest) ProtoMessage() {}

func (x *UpgradeMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeMemberRequest.ProtoReflect.Descriptor instead.
func (*UpgradeMemberRequest) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{2}
}

func (x *UpgradeMemberRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpgradeMemberRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UpgradeMemberRequest) GetDurationDays() int32 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

func (x *UpgradeMemberRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *UpgradeMemberRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UpgradeMemberRequest) GetPayChannel() string {
	if x != nil {
		return x.PayChannel
	}
	return ""
}

type UpgradeMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeMemberResponse) Reset() {
	*x = UpgradeMemberResponse{}
	mi := &file_member_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeMemberResponse) ProtoMessage() {}

func (x *UpgradeMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeMemberResponse.ProtoReflect.Descriptor instead.
func (*UpgradeMemberResponse) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{3}
}

type CheckMemberRightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	RightKey      string                 `protobuf:"bytes,2,opt,name=rightKey,proto3" json:"rightKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckMemberRightRequest) Reset() {
	*x = CheckMemberRightRequest{}
	mi := &file_member_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckMemberRightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMemberRightRequest) ProtoMessage() {}

func (x *CheckMemberRightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMemberRightRequest.ProtoReflect.Descriptor instead.
func (*CheckMemberRightRequest) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{4}
}

func (x *CheckMemberRightRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckMemberRightRequest) GetRightKey() string {
	if x != nil {
		return x.RightKey
	}
	return ""
}

type CheckMemberRightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasRight      bool                   `protobuf:"varint,1,opt,name=hasRight,proto3" json:"hasRight,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckMemberRightResponse) Reset() {
	*x = CheckMemberRightResponse{}
	mi := &file_member_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckMemberRightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMemberRightResponse) ProtoMessage() {}

func (x *CheckMemberRightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMemberRightResponse.ProtoReflect.Descriptor instead.
func (*CheckMemberRightResponse) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{5}
}

func (x *CheckMemberRightResponse) GetHasRight() bool {
	if x != nil {
		return x.HasRight
	}
	return false
}

func (x *CheckMemberRightResponse) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type MemberOrderListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberOrderListRequest) Reset() {
	*x = MemberOrderListRequest{}
	mi := &file_member_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberOrderListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberOrderListRequest) ProtoMessage() {}

func (x *MemberOrderListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberOrderListRequest.ProtoReflect.Descriptor instead.
func (*MemberOrderListRequest) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{6}
}

func (x *MemberOrderListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MemberOrderListRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *MemberOrderListRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type MemberOrderListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MemberOrderItem     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	IsEnd         bool                   `protobuf:"varint,3,opt,name=isEnd,proto3" json:"isEnd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberOrderListResponse) Reset() {
	*x = MemberOrderListResponse{}
	mi := &file_member_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberOrderListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberOrderListResponse) ProtoMessage() {}

func (x *MemberOrderListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberOrderListResponse.ProtoReflect.Descriptor instead.
func (*MemberOrderListResponse) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{7}
}

func (x *MemberOrderListResponse) GetItems() []*MemberOrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *MemberOrderListResponse) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *MemberOrderListResponse) GetIsEnd() bool {
	if x != nil {
		return x.IsEnd
	}
	return false
}

type MemberOrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	DurationDays  int32                  `protobuf:"varint,4,opt,name=durationDays,proto3" json:"durationDays,omitempty"`
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	PayChannel    string                 `protobuf:"bytes,6,opt,name=payChannel,proto3" json:"payChannel,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime    int64                  `protobuf:"varint,8,opt,name=createTime,proto3" json:"createTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberOrderItem) Reset() {
	*x = MemberOrderItem{}
	mi := &file_member_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberOrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberOrderItem) ProtoMessage() {}

func (x *MemberOrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberOrderItem.ProtoReflect.Descriptor instead.
func (*MemberOrderItem) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{8}
}

func (x *MemberOrderItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MemberOrderItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MemberOrderItem) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *MemberOrderItem) GetDurationDays() int32 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

func (x *MemberOrderItem) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *MemberOrderItem) GetPayChannel() string {
	if x != nil {
		return x.PayChannel
	}
	return ""
}

func (x *MemberOrderItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MemberOrderItem) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	DurationDays  int32                  `protobuf:"varint,3,opt,name=durationDays,proto3" json:"durationDays,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	PayChannel    string                 `protobuf:"bytes,5,opt,name=payChannel,proto3" json:"payChannel,omitempty"`
	PlanId        int32                  `protobuf:"varint,6,opt,name=planId,proto3" json:"planId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_member_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{9}
}

func (x *CreateOrderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOrderRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CreateOrderRequest) GetDurationDays() int32 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

func (x *CreateOrderRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateOrderRequest) GetPayChannel() string {
	if x != nil {
		return x.PayChannel
	}
	return ""
}

func (x *CreateOrderRequest) GetPlanId() int32 {
	if x != nil {
		return x.PlanId
	}
	return 0
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderSn       string                 `protobuf:"bytes,1,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_member_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{10}
}

func (x *CreateOrderResponse) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *CreateOrderResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type PayCallbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderSn       string                 `protobuf:"bytes,1,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayCallbackRequest) Reset() {
	*x = PayCallbackRequest{}
	mi := &file_member_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayCallbackRequest) ProtoMessage() {}

func (x *PayCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayCallbackRequest.ProtoReflect.Descriptor instead.
func (*PayCallbackRequest) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{11}
}

func (x *PayCallbackRequest) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *PayCallbackRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type PayCallbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayCallbackResponse) Reset() {
	*x = PayCallbackResponse{}
	mi := &file_member_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayCallbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayCallbackResponse) ProtoMessage() {}

func (x *PayCallbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayCallbackResponse.ProtoReflect.Descriptor instead.
func (*PayCallbackResponse) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{12}
}

var File_member_proto protoreflect.FileDescriptor

const file_member_proto_rawDesc = "" +
	"\n" +
	"\fmember.proto\x12\x02pb\"+\n" +
	"\x11MemberInfoRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"\x98\x01\n" +
	"\x12MemberInfoResponse\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12\x1c\n" +
	"\tlevelName\x18\x03 \x01(\tR\tlevelName\x12\x1e\n" +
	"\n" +
	"expireTime\x18\x04 \x01(\x03R\n" +
	"expireTime\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\"\xc6\x01\n" +
	"\x14UpgradeMemberRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12\"\n" +
	"\fdurationDays\x18\x03 \x01(\x05R\fdurationDays\x12$\n" +
	"\rtransactionId\x18\x04 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12\x1e\n" +
	"\n" +
	"payChannel\x18\x06 \x01(\tR\n" +
	"payChannel\"\x17\n" +
	"\x15UpgradeMemberResponse\"M\n" +
	"\x17CheckMemberRightRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\brightKey\x18\x02 \x01(\tR\brightKey\"L\n" +
	"\x18CheckMemberRightResponse\x12\x1a\n" +
	"\bhasRight\x18\x01 \x01(\bR\bhasRight\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\"d\n" +
	"\x16MemberOrderListRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x03R\bpageSize\"r\n" +
	"\x17MemberOrderListResponse\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.pb.MemberOrderItemR\x05items\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05isEnd\x18\x03 \x01(\bR\x05isEnd\"\xe3\x01\n" +
	"\x0fMemberOrderItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\"\n" +
	"\fdurationDays\x18\x04 \x01(\x05R\fdurationDays\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12\x1e\n" +
	"\n" +
	"payChannel\x18\x06 \x01(\tR\n" +
	"payChannel\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x1e\n" +
	"\n" +
	"createTime\x18\b \x01(\x03R\n" +
	"createTime\"\x9e\x01\n" +
	"\x12CreateOrderRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12\"\n" +
	"\fdurationDays\x18\x03 \x01(\x05R\fdurationDays\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x1e\n" +
	"\n" +
	"payChannel\x18\x05 \x01(\tR\n" +
	"payChannel\"G\n" +
	"\x13CreateOrderResponse\x12\x18\n" +
	"\aorderSn\x18\x01 \x01(\tR\aorderSn\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"T\n" +
	"\x12PayCallbackRequest\x12\x18\n" +
	"\aorderSn\x18\x01 \x01(\tR\aorderSn\x12$\n" +
	"\rtransactionId\x18\x02 \x01(\tR\rtransactionId\"\x15\n" +
	"\x13PayCallbackResponse2\xa6\x03\n" +
	"\x06Member\x12;\n" +
	"\n" +
	"MemberInfo\x12\x15.pb.MemberInfoRequest\x1a\x16.pb.MemberInfoResponse\x12D\n" +
	"\rUpgradeMember\x12\x18.pb.UpgradeMemberRequest\x1a\x19.pb.UpgradeMemberResponse\x12M\n" +
	"\x10CheckMemberRight\x12\x1b.pb.CheckMemberRightRequest\x1a\x1c.pb.CheckMemberRightResponse\x12J\n" +
	"\x0fMemberOrderList\x12\x1a.pb.MemberOrderListRequest\x1a\x1b.pb.MemberOrderListResponse\x12>\n" +
	"\vCreateOrder\x12\x16.pb.CreateOrderRequest\x1a\x17.pb.CreateOrderResponse\x12>\n" +
	"\vPayCallback\x12\x16.pb.PayCallbackRequest\x1a\x17.pb.PayCallbackResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_member_proto_rawDescOnce sync.Once
	file_member_proto_rawDescData []byte
)

func file_member_proto_rawDescGZIP() []byte {
	file_member_proto_rawDescOnce.Do(func() {
		file_member_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_member_proto_rawDesc), len(file_member_proto_rawDesc)))
	})
	return file_member_proto_rawDescData
}

var file_member_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_member_proto_goTypes = []any{
	(*MemberInfoRequest)(nil),        // 0: pb.MemberInfoRequest
	(*MemberInfoResponse)(nil),       // 1: pb.MemberInfoResponse
	(*UpgradeMemberRequest)(nil),     // 2: pb.UpgradeMemberRequest
	(*UpgradeMemberResponse)(nil),    // 3: pb.UpgradeMemberResponse
	(*CheckMemberRightRequest)(nil),  // 4: pb.CheckMemberRightRequest
	(*CheckMemberRightResponse)(nil), // 5: pb.CheckMemberRightResponse
	(*MemberOrderListRequest)(nil),   // 6: pb.MemberOrderListRequest
	(*MemberOrderListResponse)(nil),  // 7: pb.MemberOrderListResponse
	(*MemberOrderItem)(nil),          // 8: pb.MemberOrderItem
	(*CreateOrderRequest)(nil),       // 9: pb.CreateOrderRequest
	(*CreateOrderResponse)(nil),      // 10: pb.CreateOrderResponse
	(*PayCallbackRequest)(nil),       // 11: pb.PayCallbackRequest
	(*PayCallbackResponse)(nil),      // 12: pb.PayCallbackResponse
}
var file_member_proto_depIdxs = []int32{
	8,  // 0: pb.MemberOrderListResponse.items:type_name -> pb.MemberOrderItem
	0,  // 1: pb.Member.MemberInfo:input_type -> pb.MemberInfoRequest
	2,  // 2: pb.Member.UpgradeMember:input_type -> pb.UpgradeMemberRequest
	4,  // 3: pb.Member.CheckMemberRight:input_type -> pb.CheckMemberRightRequest
	6,  // 4: pb.Member.MemberOrderList:input_type -> pb.MemberOrderListRequest
	9,  // 5: pb.Member.CreateOrder:input_type -> pb.CreateOrderRequest
	11, // 6: pb.Member.PayCallback:input_type -> pb.PayCallbackRequest
	1,  // 7: pb.Member.MemberInfo:output_type -> pb.MemberInfoResponse
	3,  // 8: pb.Member.UpgradeMember:output_type -> pb.UpgradeMemberResponse
	5,  // 9: pb.Member.CheckMemberRight:output_type -> pb.CheckMemberRightResponse
	7,  // 10: pb.Member.MemberOrderList:output_type -> pb.MemberOrderListResponse
	10, // 11: pb.Member.CreateOrder:output_type -> pb.CreateOrderResponse
	12, // 12: pb.Member.PayCallback:output_type -> pb.PayCallbackResponse
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_member_proto_init() }
func file_member_proto_init() {
	if File_member_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_member_proto_rawDesc), len(file_member_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_member_proto_goTypes,
		DependencyIndexes: file_member_proto_depIdxs,
		MessageInfos:      file_member_proto_msgTypes,
	}.Build()
	File_member_proto = out.File
	file_member_proto_goTypes = nil
	file_member_proto_depIdxs = nil
}
