// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Mobile        string                 `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *RegisterRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterData) Reset() {
	*x = RegisterData{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterData) ProtoMessage() {}

func (x *RegisterData) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterData.ProtoReflect.Descriptor instead.
func (*RegisterData) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterData) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *RegisterData          `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RegisterResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *RegisterResponse) GetData() *RegisterData {
	if x != nil {
		return x.Data
	}
	return nil
}

type FindByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdRequest) Reset() {
	*x = FindByIdRequest{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdRequest) ProtoMessage() {}

func (x *FindByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdRequest.ProtoReflect.Descriptor instead.
func (*FindByIdRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *FindByIdRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UserInfoData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Mobile        string                 `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Role          int64                  `protobuf:"varint,5,opt,name=role,proto3" json:"role,omitempty"`
	DisplayId     string                 `protobuf:"bytes,6,opt,name=displayId,proto3" json:"displayId,omitempty"`
	Bio           string                 `protobuf:"bytes,7,opt,name=bio,proto3" json:"bio,omitempty"`
	Gender        int32                  `protobuf:"varint,8,opt,name=gender,proto3" json:"gender,omitempty"`
	ProfileCover  string                 `protobuf:"bytes,9,opt,name=profileCover,proto3" json:"profileCover,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoData) Reset() {
	*x = UserInfoData{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoData) ProtoMessage() {}

func (x *UserInfoData) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoData.ProtoReflect.Descriptor instead.
func (*UserInfoData) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserInfoData) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserInfoData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfoData) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *UserInfoData) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfoData) GetRole() int64 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *UserInfoData) GetDisplayId() string {
	if x != nil {
		return x.DisplayId
	}
	return ""
}

func (x *UserInfoData) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UserInfoData) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UserInfoData) GetProfileCover() string {
	if x != nil {
		return x.ProfileCover
	}
	return ""
}

type FindByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *UserInfoData          `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdResponse) Reset() {
	*x = FindByIdResponse{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdResponse) ProtoMessage() {}

func (x *FindByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdResponse.ProtoReflect.Descriptor instead.
func (*FindByIdResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *FindByIdResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FindByIdResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *FindByIdResponse) GetData() *UserInfoData {
	if x != nil {
		return x.Data
	}
	return nil
}

type FindByMobileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByMobileRequest) Reset() {
	*x = FindByMobileRequest{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByMobileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByMobileRequest) ProtoMessage() {}

func (x *FindByMobileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByMobileRequest.ProtoReflect.Descriptor instead.
func (*FindByMobileRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *FindByMobileRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

type UserAuthData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Mobile        string                 `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Role          int64                  `protobuf:"varint,6,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAuthData) Reset() {
	*x = UserAuthData{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAuthData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuthData) ProtoMessage() {}

func (x *UserAuthData) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuthData.ProtoReflect.Descriptor instead.
func (*UserAuthData) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *UserAuthData) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserAuthData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserAuthData) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *UserAuthData) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserAuthData) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserAuthData) GetRole() int64 {
	if x != nil {
		return x.Role
	}
	return 0
}

type FindByMobileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *UserAuthData          `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByMobileResponse) Reset() {
	*x = FindByMobileResponse{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByMobileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByMobileResponse) ProtoMessage() {}

func (x *FindByMobileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByMobileResponse.ProtoReflect.Descriptor instead.
func (*FindByMobileResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *FindByMobileResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FindByMobileResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *FindByMobileResponse) GetData() *UserAuthData {
	if x != nil {
		return x.Data
	}
	return nil
}

type SendSmsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Mobile        string                 `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsRequest) Reset() {
	*x = SendSmsRequest{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsRequest) ProtoMessage() {}

func (x *SendSmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsRequest.ProtoReflect.Descriptor instead.
func (*SendSmsRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *SendSmsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SendSmsRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

type SendSmsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsResponse) Reset() {
	*x = SendSmsResponse{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsResponse) ProtoMessage() {}

func (x *SendSmsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsResponse.ProtoReflect.Descriptor instead.
func (*SendSmsResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *SendSmsResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendSmsResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Bio           string                 `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	Gender        int32                  `protobuf:"varint,5,opt,name=gender,proto3" json:"gender,omitempty"`
	ProfileCover  string                 `protobuf:"bytes,6,opt,name=profileCover,proto3" json:"profileCover,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateProfileRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateProfileRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateProfileRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateProfileRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UpdateProfileRequest) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UpdateProfileRequest) GetProfileCover() string {
	if x != nil {
		return x.ProfileCover
	}
	return ""
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateProfileResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateProfileResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UpgradePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,2,opt,name=passwordHash,proto3" json:"passwordHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradePasswordRequest) Reset() {
	*x = UpgradePasswordRequest{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradePasswordRequest) ProtoMessage() {}

func (x *UpgradePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradePasswordRequest.ProtoReflect.Descriptor instead.
func (*UpgradePasswordRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

func (x *UpgradePasswordRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpgradePasswordRequest) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

type UpgradePasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradePasswordResponse) Reset() {
	*x = UpgradePasswordResponse{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradePasswordResponse) ProtoMessage() {}

func (x *UpgradePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradePasswordResponse.ProtoReflect.Descriptor instead.
func (*UpgradePasswordResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

func (x *UpgradePasswordResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpgradePasswordResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type AdminUserListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserListRequest) Reset() {
	*x = AdminUserListRequest{}
	mi := &file_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserListRequest) ProtoMessage() {}

func (x *AdminUserListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserListRequest.ProtoReflect.Descriptor instead.
func (*AdminUserListRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{15}
}

func (x *AdminUserListRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *AdminUserListRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *AdminUserListRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type AdminUserListData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserInfoData        `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	IsEnd         bool                   `protobuf:"varint,3,opt,name=isEnd,proto3" json:"isEnd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserListData) Reset() {
	*x = AdminUserListData{}
	mi := &file_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserListData) ProtoMessage() {}

func (x *AdminUserListData) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserListData.ProtoReflect.Descriptor instead.
func (*AdminUserListData) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{16}
}

func (x *AdminUserListData) GetUsers() []*UserInfoData {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *AdminUserListData) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *AdminUserListData) GetIsEnd() bool {
	if x != nil {
		return x.IsEnd
	}
	return false
}

type AdminUserListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *AdminUserListData     `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserListResponse) Reset() {
	*x = AdminUserListResponse{}
	mi := &file_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserListResponse) ProtoMessage() {}

func (x *AdminUserListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserListResponse.ProtoReflect.Descriptor instead.
func (*AdminUserListResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{17}
}

func (x *AdminUserListResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AdminUserListResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *AdminUserListResponse) GetData() *AdminUserListData {
	if x != nil {
		return x.Data
	}
	return nil
}

type MemberInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberInfoRequest) Reset() {
	*x = MemberInfoRequest{}
	mi := &file_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberInfoRequest) ProtoMessage() {}

func (x *MemberInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberInfoRequest.ProtoReflect.Descriptor instead.
func (*MemberInfoRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{18}
}

func (x *MemberInfoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type MemberInfoData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	LevelName     string                 `protobuf:"bytes,3,opt,name=levelName,proto3" json:"levelName,omitempty"`
	ExpireTime    int64                  `protobuf:"varint,4,opt,name=expireTime,proto3" json:"expireTime,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberInfoData) Reset() {
	*x = MemberInfoData{}
	mi := &file_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberInfoData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberInfoData) ProtoMessage() {}

func (x *MemberInfoData) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberInfoData.ProtoReflect.Descriptor instead.
func (*MemberInfoData) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{19}
}

func (x *MemberInfoData) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MemberInfoData) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *MemberInfoData) GetLevelName() string {
	if x != nil {
		return x.LevelName
	}
	return ""
}

func (x *MemberInfoData) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *MemberInfoData) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type MemberInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *MemberInfoData        `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberInfoResponse) Reset() {
	*x = MemberInfoResponse{}
	mi := &file_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberInfoResponse) ProtoMessage() {}

func (x *MemberInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberInfoResponse.ProtoReflect.Descriptor instead.
func (*MemberInfoResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{20}
}

func (x *MemberInfoResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MemberInfoResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *MemberInfoResponse) GetData() *MemberInfoData {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpgradeMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	DurationDays  int32                  `protobuf:"varint,3,opt,name=durationDays,proto3" json:"durationDays,omitempty"`
	TransactionId string                 `protobuf:"bytes,4,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	PayChannel    string                 `protobuf:"bytes,6,opt,name=payChannel,proto3" json:"payChannel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeMemberRequest) Reset() {
	*x = UpgradeMemberRequest{}
	mi := &file_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeMemberRequest) ProtoMessage() {}

func (x *UpgradeMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeMemberRequest.ProtoReflect.Descriptor instead.
func (*UpgradeMemberRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{21}
}

func (x *UpgradeMemberRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpgradeMemberRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UpgradeMemberRequest) GetDurationDays() int32 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

func (x *UpgradeMemberRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *UpgradeMemberRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UpgradeMemberRequest) GetPayChannel() string {
	if x != nil {
		return x.PayChannel
	}
	return ""
}

type UpgradeMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeMemberResponse) Reset() {
	*x = UpgradeMemberResponse{}
	mi := &file_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeMemberResponse) ProtoMessage() {}

func (x *UpgradeMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeMemberResponse.ProtoReflect.Descriptor instead.
func (*UpgradeMemberResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{22}
}

func (x *UpgradeMemberResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpgradeMemberResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CheckMemberRightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	RightKey      string                 `protobuf:"bytes,2,opt,name=rightKey,proto3" json:"rightKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckMemberRightRequest) Reset() {
	*x = CheckMemberRightRequest{}
	mi := &file_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckMemberRightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMemberRightRequest) ProtoMessage() {}

func (x *CheckMemberRightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMemberRightRequest.ProtoReflect.Descriptor instead.
func (*CheckMemberRightRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{23}
}

func (x *CheckMemberRightRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckMemberRightRequest) GetRightKey() string {
	if x != nil {
		return x.RightKey
	}
	return ""
}

type CheckMemberRightData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasRight      bool                   `protobuf:"varint,1,opt,name=hasRight,proto3" json:"hasRight,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckMemberRightData) Reset() {
	*x = CheckMemberRightData{}
	mi := &file_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckMemberRightData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMemberRightData) ProtoMessage() {}

func (x *CheckMemberRightData) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMemberRightData.ProtoReflect.Descriptor instead.
func (*CheckMemberRightData) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{24}
}

func (x *CheckMemberRightData) GetHasRight() bool {
	if x != nil {
		return x.HasRight
	}
	return false
}

func (x *CheckMemberRightData) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type CheckMemberRightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *CheckMemberRightData  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckMemberRightResponse) Reset() {
	*x = CheckMemberRightResponse{}
	mi := &file_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckMemberRightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMemberRightResponse) ProtoMessage() {}

func (x *CheckMemberRightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMemberRightResponse.ProtoReflect.Descriptor instead.
func (*CheckMemberRightResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{25}
}

func (x *CheckMemberRightResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CheckMemberRightResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CheckMemberRightResponse) GetData() *CheckMemberRightData {
	if x != nil {
		return x.Data
	}
	return nil
}

type MemberOrderListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberOrderListRequest) Reset() {
	*x = MemberOrderListRequest{}
	mi := &file_user_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberOrderListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberOrderListRequest) ProtoMessage() {}

func (x *MemberOrderListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberOrderListRequest.ProtoReflect.Descriptor instead.
func (*MemberOrderListRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{26}
}

func (x *MemberOrderListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MemberOrderListRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *MemberOrderListRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type MemberOrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	DurationDays  int32                  `protobuf:"varint,4,opt,name=durationDays,proto3" json:"durationDays,omitempty"`
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	PayChannel    string                 `protobuf:"bytes,6,opt,name=payChannel,proto3" json:"payChannel,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime    int64                  `protobuf:"varint,8,opt,name=createTime,proto3" json:"createTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberOrderItem) Reset() {
	*x = MemberOrderItem{}
	mi := &file_user_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberOrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberOrderItem) ProtoMessage() {}

func (x *MemberOrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberOrderItem.ProtoReflect.Descriptor instead.
func (*MemberOrderItem) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{27}
}

func (x *MemberOrderItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MemberOrderItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MemberOrderItem) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *MemberOrderItem) GetDurationDays() int32 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

func (x *MemberOrderItem) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *MemberOrderItem) GetPayChannel() string {
	if x != nil {
		return x.PayChannel
	}
	return ""
}

func (x *MemberOrderItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MemberOrderItem) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type MemberOrderListData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MemberOrderItem     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	IsEnd         bool                   `protobuf:"varint,3,opt,name=isEnd,proto3" json:"isEnd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberOrderListData) Reset() {
	*x = MemberOrderListData{}
	mi := &file_user_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberOrderListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberOrderListData) ProtoMessage() {}

func (x *MemberOrderListData) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberOrderListData.ProtoReflect.Descriptor instead.
func (*MemberOrderListData) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{28}
}

func (x *MemberOrderListData) GetItems() []*MemberOrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *MemberOrderListData) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *MemberOrderListData) GetIsEnd() bool {
	if x != nil {
		return x.IsEnd
	}
	return false
}

type MemberOrderListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *MemberOrderListData   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberOrderListResponse) Reset() {
	*x = MemberOrderListResponse{}
	mi := &file_user_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberOrderListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberOrderListResponse) ProtoMessage() {}

func (x *MemberOrderListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberOrderListResponse.ProtoReflect.Descriptor instead.
func (*MemberOrderListResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{29}
}

func (x *MemberOrderListResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MemberOrderListResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *MemberOrderListResponse) GetData() *MemberOrderListData {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	DurationDays  int32                  `protobuf:"varint,3,opt,name=durationDays,proto3" json:"durationDays,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	PayChannel    string                 `protobuf:"bytes,5,opt,name=payChannel,proto3" json:"payChannel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_user_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{30}
}

func (x *CreateOrderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOrderRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CreateOrderRequest) GetDurationDays() int32 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

func (x *CreateOrderRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateOrderRequest) GetPayChannel() string {
	if x != nil {
		return x.PayChannel
	}
	return ""
}

type CreateOrderData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderSn       string                 `protobuf:"bytes,1,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderData) Reset() {
	*x = CreateOrderData{}
	mi := &file_user_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderData) ProtoMessage() {}

func (x *CreateOrderData) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderData.ProtoReflect.Descriptor instead.
func (*CreateOrderData) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{31}
}

func (x *CreateOrderData) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *CreateOrderData) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *CreateOrderData       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_user_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{32}
}

func (x *CreateOrderResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateOrderResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CreateOrderResponse) GetData() *CreateOrderData {
	if x != nil {
		return x.Data
	}
	return nil
}

type PayCallbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderSn       string                 `protobuf:"bytes,1,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayCallbackRequest) Reset() {
	*x = PayCallbackRequest{}
	mi := &file_user_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayCallbackRequest) ProtoMessage() {}

func (x *PayCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayCallbackRequest.ProtoReflect.Descriptor instead.
func (*PayCallbackRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{33}
}

func (x *PayCallbackRequest) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *PayCallbackRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type PayCallbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayCallbackResponse) Reset() {
	*x = PayCallbackResponse{}
	mi := &file_user_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayCallbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayCallbackResponse) ProtoMessage() {}

func (x *PayCallbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayCallbackResponse.ProtoReflect.Descriptor instead.
func (*PayCallbackResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{34}
}

func (x *PayCallbackResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PayCallbackResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type FollowRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FollowedUserId int64                  `protobuf:"varint,2,opt,name=followedUserId,proto3" json:"followedUserId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FollowRequest) Reset() {
	*x = FollowRequest{}
	mi := &file_user_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowRequest) ProtoMessage() {}

func (x *FollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowRequest.ProtoReflect.Descriptor instead.
func (*FollowRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{35}
}

func (x *FollowRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FollowRequest) GetFollowedUserId() int64 {
	if x != nil {
		return x.FollowedUserId
	}
	return 0
}

type FollowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowResponse) Reset() {
	*x = FollowResponse{}
	mi := &file_user_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowResponse) ProtoMessage() {}

func (x *FollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowResponse.ProtoReflect.Descriptor instead.
func (*FollowResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{36}
}

func (x *FollowResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FollowResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UnFollowRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FollowedUserId int64                  `protobuf:"varint,2,opt,name=followedUserId,proto3" json:"followedUserId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UnFollowRequest) Reset() {
	*x = UnFollowRequest{}
	mi := &file_user_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnFollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnFollowRequest) ProtoMessage() {}

func (x *UnFollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnFollowRequest.ProtoReflect.Descriptor instead.
func (*UnFollowRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{37}
}

func (x *UnFollowRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UnFollowRequest) GetFollowedUserId() int64 {
	if x != nil {
		return x.FollowedUserId
	}
	return 0
}

type UnFollowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnFollowResponse) Reset() {
	*x = UnFollowResponse{}
	mi := &file_user_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnFollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnFollowResponse) ProtoMessage() {}

func (x *UnFollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnFollowResponse.ProtoReflect.Descriptor instead.
func (*UnFollowResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{38}
}

func (x *UnFollowResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UnFollowResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type FollowListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Cursor        int64                  `protobuf:"varint,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize      int64                  `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowListRequest) Reset() {
	*x = FollowListRequest{}
	mi := &file_user_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowListRequest) ProtoMessage() {}

func (x *FollowListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowListRequest.ProtoReflect.Descriptor instead.
func (*FollowListRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{39}
}

func (x *FollowListRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FollowListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FollowListRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *FollowListRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type FollowItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FollowedUserId int64                  `protobuf:"varint,2,opt,name=followedUserId,proto3" json:"followedUserId,omitempty"`
	FansCount      int64                  `protobuf:"varint,3,opt,name=fansCount,proto3" json:"fansCount,omitempty"`
	CreateTime     int64                  `protobuf:"varint,4,opt,name=createTime,proto3" json:"createTime,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FollowItem) Reset() {
	*x = FollowItem{}
	mi := &file_user_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowItem) ProtoMessage() {}

func (x *FollowItem) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowItem.ProtoReflect.Descriptor instead.
func (*FollowItem) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{40}
}

func (x *FollowItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FollowItem) GetFollowedUserId() int64 {
	if x != nil {
		return x.FollowedUserId
	}
	return 0
}

func (x *FollowItem) GetFansCount() int64 {
	if x != nil {
		return x.FansCount
	}
	return 0
}

func (x *FollowItem) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type FollowListData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*FollowItem          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	IsEnd         bool                   `protobuf:"varint,3,opt,name=isEnd,proto3" json:"isEnd,omitempty"`
	Id            int64                  `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowListData) Reset() {
	*x = FollowListData{}
	mi := &file_user_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowListData) ProtoMessage() {}

func (x *FollowListData) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowListData.ProtoReflect.Descriptor instead.
func (*FollowListData) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{41}
}

func (x *FollowListData) GetItems() []*FollowItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *FollowListData) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *FollowListData) GetIsEnd() bool {
	if x != nil {
		return x.IsEnd
	}
	return false
}

func (x *FollowListData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FollowListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *FollowListData        `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowListResponse) Reset() {
	*x = FollowListResponse{}
	mi := &file_user_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowListResponse) ProtoMessage() {}

func (x *FollowListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowListResponse.ProtoReflect.Descriptor instead.
func (*FollowListResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{42}
}

func (x *FollowListResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FollowListResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *FollowListResponse) GetData() *FollowListData {
	if x != nil {
		return x.Data
	}
	return nil
}

type FansListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Cursor        int64                  `protobuf:"varint,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize      int64                  `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FansListRequest) Reset() {
	*x = FansListRequest{}
	mi := &file_user_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FansListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FansListRequest) ProtoMessage() {}

func (x *FansListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FansListRequest.ProtoReflect.Descriptor instead.
func (*FansListRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{43}
}

func (x *FansListRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FansListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FansListRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *FansListRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type FansItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	FansUserId    int64                  `protobuf:"varint,3,opt,name=fansUserId,proto3" json:"fansUserId,omitempty"`
	FollowCount   int64                  `protobuf:"varint,4,opt,name=followCount,proto3" json:"followCount,omitempty"`
	FansCount     int64                  `protobuf:"varint,5,opt,name=fansCount,proto3" json:"fansCount,omitempty"`
	CreateTime    int64                  `protobuf:"varint,6,opt,name=createTime,proto3" json:"createTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FansItem) Reset() {
	*x = FansItem{}
	mi := &file_user_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FansItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FansItem) ProtoMessage() {}

func (x *FansItem) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FansItem.ProtoReflect.Descriptor instead.
func (*FansItem) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{44}
}

func (x *FansItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FansItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FansItem) GetFansUserId() int64 {
	if x != nil {
		return x.FansUserId
	}
	return 0
}

func (x *FansItem) GetFollowCount() int64 {
	if x != nil {
		return x.FollowCount
	}
	return 0
}

func (x *FansItem) GetFansCount() int64 {
	if x != nil {
		return x.FansCount
	}
	return 0
}

func (x *FansItem) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type FansListData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*FansItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	IsEnd         bool                   `protobuf:"varint,3,opt,name=isEnd,proto3" json:"isEnd,omitempty"`
	Id            int64                  `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FansListData) Reset() {
	*x = FansListData{}
	mi := &file_user_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FansListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FansListData) ProtoMessage() {}

func (x *FansListData) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FansListData.ProtoReflect.Descriptor instead.
func (*FansListData) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{45}
}

func (x *FansListData) GetItems() []*FansItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *FansListData) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *FansListData) GetIsEnd() bool {
	if x != nil {
		return x.IsEnd
	}
	return false
}

func (x *FansListData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FansListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *FansListData          `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FansListResponse) Reset() {
	*x = FansListResponse{}
	mi := &file_user_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FansListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FansListResponse) ProtoMessage() {}

func (x *FansListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FansListResponse.ProtoReflect.Descriptor instead.
func (*FansListResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{46}
}

func (x *FansListResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FansListResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *FansListResponse) GetData() *FansListData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\"y\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x16\n" +
	"\x06mobile\x18\x02 \x01(\tR\x06mobile\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"&\n" +
	"\fRegisterData\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"`\n" +
	"\x10RegisterResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12&\n" +
	"\x04data\x18\x03 \x01(\v2\x12.user.RegisterDataR\x04data\")\n" +
	"\x0fFindByIdRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"\xf2\x01\n" +
	"\fUserInfoData\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x16\n" +
	"\x06mobile\x18\x03 \x01(\tR\x06mobile\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x12\n" +
	"\x04role\x18\x05 \x01(\x03R\x04role\x12\x1c\n" +
	"\tdisplayId\x18\x06 \x01(\tR\tdisplayId\x12\x10\n" +
	"\x03bio\x18\a \x01(\tR\x03bio\x12\x16\n" +
	"\x06gender\x18\b \x01(\x05R\x06gender\x12\"\n" +
	"\fprofileCover\x18\t \x01(\tR\fprofileCover\"`\n" +
	"\x10FindByIdResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12&\n" +
	"\x04data\x18\x03 \x01(\v2\x12.user.UserInfoDataR\x04data\"-\n" +
	"\x13FindByMobileRequest\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\"\xa2\x01\n" +
	"\fUserAuthData\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x16\n" +
	"\x06mobile\x18\x03 \x01(\tR\x06mobile\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x12\n" +
	"\x04role\x18\x06 \x01(\x03R\x04role\"d\n" +
	"\x14FindByMobileResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12&\n" +
	"\x04data\x18\x03 \x01(\v2\x12.user.UserAuthDataR\x04data\"@\n" +
	"\x0eSendSmsRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06mobile\x18\x02 \x01(\tR\x06mobile\"7\n" +
	"\x0fSendSmsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\xb0\x01\n" +
	"\x14UpdateProfileRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x10\n" +
	"\x03bio\x18\x04 \x01(\tR\x03bio\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\x05R\x06gender\x12\"\n" +
	"\fprofileCover\x18\x06 \x01(\tR\fprofileCover\"=\n" +
	"\x15UpdateProfileResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"T\n" +
	"\x16UpgradePasswordRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\"\n" +
	"\fpasswordHash\x18\x02 \x01(\tR\fpasswordHash\"?\n" +
	"\x17UpgradePasswordResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"d\n" +
	"\x14AdminUserListRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x03R\bpageSize\"k\n" +
	"\x11AdminUserListData\x12(\n" +
	"\x05users\x18\x01 \x03(\v2\x12.user.UserInfoDataR\x05users\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05isEnd\x18\x03 \x01(\bR\x05isEnd\"j\n" +
	"\x15AdminUserListResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.user.AdminUserListDataR\x04data\"+\n" +
	"\x11MemberInfoRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"\x94\x01\n" +
	"\x0eMemberInfoData\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12\x1c\n" +
	"\tlevelName\x18\x03 \x01(\tR\tlevelName\x12\x1e\n" +
	"\n" +
	"expireTime\x18\x04 \x01(\x03R\n" +
	"expireTime\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\"d\n" +
	"\x12MemberInfoResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.user.MemberInfoDataR\x04data\"\xc6\x01\n" +
	"\x14UpgradeMemberRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12\"\n" +
	"\fdurationDays\x18\x03 \x01(\x05R\fdurationDays\x12$\n" +
	"\rtransactionId\x18\x04 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12\x1e\n" +
	"\n" +
	"payChannel\x18\x06 \x01(\tR\n" +
	"payChannel\"=\n" +
	"\x15UpgradeMemberResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"M\n" +
	"\x17CheckMemberRightRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\brightKey\x18\x02 \x01(\tR\brightKey\"H\n" +
	"\x14CheckMemberRightData\x12\x1a\n" +
	"\bhasRight\x18\x01 \x01(\bR\bhasRight\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\"p\n" +
	"\x18CheckMemberRightResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12.\n" +
	"\x04data\x18\x03 \x01(\v2\x1a.user.CheckMemberRightDataR\x04data\"d\n" +
	"\x16MemberOrderListRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x03R\bpageSize\"\xe3\x01\n" +
	"\x0fMemberOrderItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\"\n" +
	"\fdurationDays\x18\x04 \x01(\x05R\fdurationDays\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12\x1e\n" +
	"\n" +
	"payChannel\x18\x06 \x01(\tR\n" +
	"payChannel\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x1e\n" +
	"\n" +
	"createTime\x18\b \x01(\x03R\n" +
	"createTime\"p\n" +
	"\x13MemberOrderListData\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.user.MemberOrderItemR\x05items\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05isEnd\x18\x03 \x01(\bR\x05isEnd\"n\n" +
	"\x17MemberOrderListResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12-\n" +
	"\x04data\x18\x03 \x01(\v2\x19.user.MemberOrderListDataR\x04data\"\x9e\x01\n" +
	"\x12CreateOrderRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12\"\n" +
	"\fdurationDays\x18\x03 \x01(\x05R\fdurationDays\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x1e\n" +
	"\n" +
	"payChannel\x18\x05 \x01(\tR\n" +
	"payChannel\"C\n" +
	"\x0fCreateOrderData\x12\x18\n" +
	"\aorderSn\x18\x01 \x01(\tR\aorderSn\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"f\n" +
	"\x13CreateOrderResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12)\n" +
	"\x04data\x18\x03 \x01(\v2\x15.user.CreateOrderDataR\x04data\"T\n" +
	"\x12PayCallbackRequest\x12\x18\n" +
	"\aorderSn\x18\x01 \x01(\tR\aorderSn\x12$\n" +
	"\rtransactionId\x18\x02 \x01(\tR\rtransactionId\";\n" +
	"\x13PayCallbackResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"O\n" +
	"\rFollowRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12&\n" +
	"\x0efollowedUserId\x18\x02 \x01(\x03R\x0efollowedUserId\"6\n" +
	"\x0eFollowResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"Q\n" +
	"\x0fUnFollowRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12&\n" +
	"\x0efollowedUserId\x18\x02 \x01(\x03R\x0efollowedUserId\"8\n" +
	"\x10UnFollowResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"o\n" +
	"\x11FollowListRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\x03R\x06cursor\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x03R\bpageSize\"\x82\x01\n" +
	"\n" +
	"FollowItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12&\n" +
	"\x0efollowedUserId\x18\x02 \x01(\x03R\x0efollowedUserId\x12\x1c\n" +
	"\tfansCount\x18\x03 \x01(\x03R\tfansCount\x12\x1e\n" +
	"\n" +
	"createTime\x18\x04 \x01(\x03R\n" +
	"createTime\"v\n" +
	"\x0eFollowListData\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.user.FollowItemR\x05items\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05isEnd\x18\x03 \x01(\bR\x05isEnd\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\x03R\x02id\"d\n" +
	"\x12FollowListResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.user.FollowListDataR\x04data\"m\n" +
	"\x0fFansListRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\x03R\x06cursor\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x03R\bpageSize\"\xb2\x01\n" +
	"\bFansItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x1e\n" +
	"\n" +
	"fansUserId\x18\x03 \x01(\x03R\n" +
	"fansUserId\x12 \n" +
	"\vfollowCount\x18\x04 \x01(\x03R\vfollowCount\x12\x1c\n" +
	"\tfansCount\x18\x05 \x01(\x03R\tfansCount\x12\x1e\n" +
	"\n" +
	"createTime\x18\x06 \x01(\x03R\n" +
	"createTime\"r\n" +
	"\fFansListData\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.user.FansItemR\x05items\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05isEnd\x18\x03 \x01(\bR\x05isEnd\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\x03R\x02id\"`\n" +
	"\x10FansListResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12&\n" +
	"\x04data\x18\x03 \x01(\v2\x12.user.FansListDataR\x04data2\xdf\x03\n" +
	"\x04User\x129\n" +
	"\bRegister\x12\x15.user.RegisterRequest\x1a\x16.user.RegisterResponse\x129\n" +
	"\bFindById\x12\x15.user.FindByIdRequest\x1a\x16.user.FindByIdResponse\x12E\n" +
	"\fFindByMobile\x12\x19.user.FindByMobileRequest\x1a\x1a.user.FindByMobileResponse\x126\n" +
	"\aSendSms\x12\x14.user.SendSmsRequest\x1a\x15.user.SendSmsResponse\x12H\n" +
	"\rUpdateProfile\x12\x1a.user.UpdateProfileRequest\x1a\x1b.user.UpdateProfileResponse\x12N\n" +
	"\x0fUpgradePassword\x12\x1c.user.UpgradePasswordRequest\x1a\x1d.user.UpgradePasswordResponse\x12H\n" +
	"\rAdminUserList\x12\x1a.user.AdminUserListRequest\x1a\x1b.user.AdminUserListResponse2\xbe\x03\n" +
	"\x06Member\x12?\n" +
	"\n" +
	"MemberInfo\x12\x17.user.MemberInfoRequest\x1a\x18.user.MemberInfoResponse\x12H\n" +
	"\rUpgradeMember\x12\x1a.user.UpgradeMemberRequest\x1a\x1b.user.UpgradeMemberResponse\x12Q\n" +
	"\x10CheckMemberRight\x12\x1d.user.CheckMemberRightRequest\x1a\x1e.user.CheckMemberRightResponse\x12N\n" +
	"\x0fMemberOrderList\x12\x1c.user.MemberOrderListRequest\x1a\x1d.user.MemberOrderListResponse\x12B\n" +
	"\vCreateOrder\x12\x18.user.CreateOrderRequest\x1a\x19.user.CreateOrderResponse\x12B\n" +
	"\vPayCallback\x12\x18.user.PayCallbackRequest\x1a\x19.user.PayCallbackResponse2\xf4\x01\n" +
	"\x06Follow\x123\n" +
	"\x06Follow\x12\x13.user.FollowRequest\x1a\x14.user.FollowResponse\x129\n" +
	"\bUnFollow\x12\x15.user.UnFollowRequest\x1a\x16.user.UnFollowResponse\x12?\n" +
	"\n" +
	"FollowList\x12\x17.user.FollowListRequest\x1a\x18.user.FollowListResponse\x129\n" +
	"\bFansList\x12\x15.user.FansListRequest\x1a\x16.user.FansListResponseB\bZ\x06./userb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 47)
var file_user_proto_goTypes = []any{
	(*RegisterRequest)(nil),          // 0: user.RegisterRequest
	(*RegisterData)(nil),             // 1: user.RegisterData
	(*RegisterResponse)(nil),         // 2: user.RegisterResponse
	(*FindByIdRequest)(nil),          // 3: user.FindByIdRequest
	(*UserInfoData)(nil),             // 4: user.UserInfoData
	(*FindByIdResponse)(nil),         // 5: user.FindByIdResponse
	(*FindByMobileRequest)(nil),      // 6: user.FindByMobileRequest
	(*UserAuthData)(nil),             // 7: user.UserAuthData
	(*FindByMobileResponse)(nil),     // 8: user.FindByMobileResponse
	(*SendSmsRequest)(nil),           // 9: user.SendSmsRequest
	(*SendSmsResponse)(nil),          // 10: user.SendSmsResponse
	(*UpdateProfileRequest)(nil),     // 11: user.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),    // 12: user.UpdateProfileResponse
	(*UpgradePasswordRequest)(nil),   // 13: user.UpgradePasswordRequest
	(*UpgradePasswordResponse)(nil),  // 14: user.UpgradePasswordResponse
	(*AdminUserListRequest)(nil),     // 15: user.AdminUserListRequest
	(*AdminUserListData)(nil),        // 16: user.AdminUserListData
	(*AdminUserListResponse)(nil),    // 17: user.AdminUserListResponse
	(*MemberInfoRequest)(nil),        // 18: user.MemberInfoRequest
	(*MemberInfoData)(nil),           // 19: user.MemberInfoData
	(*MemberInfoResponse)(nil),       // 20: user.MemberInfoResponse
	(*UpgradeMemberRequest)(nil),     // 21: user.UpgradeMemberRequest
	(*UpgradeMemberResponse)(nil),    // 22: user.UpgradeMemberResponse
	(*CheckMemberRightRequest)(nil),  // 23: user.CheckMemberRightRequest
	(*CheckMemberRightData)(nil),     // 24: user.CheckMemberRightData
	(*CheckMemberRightResponse)(nil), // 25: user.CheckMemberRightResponse
	(*MemberOrderListRequest)(nil),   // 26: user.MemberOrderListRequest
	(*MemberOrderItem)(nil),          // 27: user.MemberOrderItem
	(*MemberOrderListData)(nil),      // 28: user.MemberOrderListData
	(*MemberOrderListResponse)(nil),  // 29: user.MemberOrderListResponse
	(*CreateOrderRequest)(nil),       // 30: user.CreateOrderRequest
	(*CreateOrderData)(nil),          // 31: user.CreateOrderData
	(*CreateOrderResponse)(nil),      // 32: user.CreateOrderResponse
	(*PayCallbackRequest)(nil),       // 33: user.PayCallbackRequest
	(*PayCallbackResponse)(nil),      // 34: user.PayCallbackResponse
	(*FollowRequest)(nil),            // 35: user.FollowRequest
	(*FollowResponse)(nil),           // 36: user.FollowResponse
	(*UnFollowRequest)(nil),          // 37: user.UnFollowRequest
	(*UnFollowResponse)(nil),         // 38: user.UnFollowResponse
	(*FollowListRequest)(nil),        // 39: user.FollowListRequest
	(*FollowItem)(nil),               // 40: user.FollowItem
	(*FollowListData)(nil),           // 41: user.FollowListData
	(*FollowListResponse)(nil),       // 42: user.FollowListResponse
	(*FansListRequest)(nil),          // 43: user.FansListRequest
	(*FansItem)(nil),                 // 44: user.FansItem
	(*FansListData)(nil),             // 45: user.FansListData
	(*FansListResponse)(nil),         // 46: user.FansListResponse
}
var file_user_proto_depIdxs = []int32{
	1,  // 0: user.RegisterResponse.data:type_name -> user.RegisterData
	4,  // 1: user.FindByIdResponse.data:type_name -> user.UserInfoData
	7,  // 2: user.FindByMobileResponse.data:type_name -> user.UserAuthData
	4,  // 3: user.AdminUserListData.users:type_name -> user.UserInfoData
	16, // 4: user.AdminUserListResponse.data:type_name -> user.AdminUserListData
	19, // 5: user.MemberInfoResponse.data:type_name -> user.MemberInfoData
	24, // 6: user.CheckMemberRightResponse.data:type_name -> user.CheckMemberRightData
	27, // 7: user.MemberOrderListData.items:type_name -> user.MemberOrderItem
	28, // 8: user.MemberOrderListResponse.data:type_name -> user.MemberOrderListData
	31, // 9: user.CreateOrderResponse.data:type_name -> user.CreateOrderData
	40, // 10: user.FollowListData.items:type_name -> user.FollowItem
	41, // 11: user.FollowListResponse.data:type_name -> user.FollowListData
	44, // 12: user.FansListData.items:type_name -> user.FansItem
	45, // 13: user.FansListResponse.data:type_name -> user.FansListData
	0,  // 14: user.User.Register:input_type -> user.RegisterRequest
	3,  // 15: user.User.FindById:input_type -> user.FindByIdRequest
	6,  // 16: user.User.FindByMobile:input_type -> user.FindByMobileRequest
	9,  // 17: user.User.SendSms:input_type -> user.SendSmsRequest
	11, // 18: user.User.UpdateProfile:input_type -> user.UpdateProfileRequest
	13, // 19: user.User.UpgradePassword:input_type -> user.UpgradePasswordRequest
	15, // 20: user.User.AdminUserList:input_type -> user.AdminUserListRequest
	18, // 21: user.Member.MemberInfo:input_type -> user.MemberInfoRequest
	21, // 22: user.Member.UpgradeMember:input_type -> user.UpgradeMemberRequest
	23, // 23: user.Member.CheckMemberRight:input_type -> user.CheckMemberRightRequest
	26, // 24: user.Member.MemberOrderList:input_type -> user.MemberOrderListRequest
	30, // 25: user.Member.CreateOrder:input_type -> user.CreateOrderRequest
	33, // 26: user.Member.PayCallback:input_type -> user.PayCallbackRequest
	35, // 27: user.Follow.Follow:input_type -> user.FollowRequest
	37, // 28: user.Follow.UnFollow:input_type -> user.UnFollowRequest
	39, // 29: user.Follow.FollowList:input_type -> user.FollowListRequest
	43, // 30: user.Follow.FansList:input_type -> user.FansListRequest
	2,  // 31: user.User.Register:output_type -> user.RegisterResponse
	5,  // 32: user.User.FindById:output_type -> user.FindByIdResponse
	8,  // 33: user.User.FindByMobile:output_type -> user.FindByMobileResponse
	10, // 34: user.User.SendSms:output_type -> user.SendSmsResponse
	12, // 35: user.User.UpdateProfile:output_type -> user.UpdateProfileResponse
	14, // 36: user.User.UpgradePassword:output_type -> user.UpgradePasswordResponse
	17, // 37: user.User.AdminUserList:output_type -> user.AdminUserListResponse
	20, // 38: user.Member.MemberInfo:output_type -> user.MemberInfoResponse
	22, // 39: user.Member.UpgradeMember:output_type -> user.UpgradeMemberResponse
	25, // 40: user.Member.CheckMemberRight:output_type -> user.CheckMemberRightResponse
	29, // 41: user.Member.MemberOrderList:output_type -> user.MemberOrderListResponse
	32, // 42: user.Member.CreateOrder:output_type -> user.CreateOrderResponse
	34, // 43: user.Member.PayCallback:output_type -> user.PayCallbackResponse
	36, // 44: user.Follow.Follow:output_type -> user.FollowResponse
	38, // 45: user.Follow.UnFollow:output_type -> user.UnFollowResponse
	42, // 46: user.Follow.FollowList:output_type -> user.FollowListResponse
	46, // 47: user.Follow.FansList:output_type -> user.FansListResponse
	31, // [31:48] is the sub-list for method output_type
	14, // [14:31] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   47,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
