// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package server

import (
	"context"

	"rpc-user/internal/logic/user"
	"rpc-user/internal/svc"
	"rpc-user/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Register(ctx context.Context, in *user.RegisterRequest) (*user.RegisterResponse, error) {
	l := userlogic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) FindById(ctx context.Context, in *user.FindByIdRequest) (*user.FindByIdResponse, error) {
	l := userlogic.NewFindByIdLogic(ctx, s.svcCtx)
	return l.FindById(in)
}

func (s *UserServer) FindByMobile(ctx context.Context, in *user.FindByMobileRequest) (*user.FindByMobileResponse, error) {
	l := userlogic.NewFindByMobileLogic(ctx, s.svcCtx)
	return l.FindByMobile(in)
}

func (s *UserServer) SendSms(ctx context.Context, in *user.SendSmsRequest) (*user.SendSmsResponse, error) {
	l := userlogic.NewSendSmsLogic(ctx, s.svcCtx)
	return l.SendSms(in)
}

func (s *UserServer) UpdateProfile(ctx context.Context, in *user.UpdateProfileRequest) (*user.UpdateProfileResponse, error) {
	l := userlogic.NewUpdateProfileLogic(ctx, s.svcCtx)
	return l.UpdateProfile(in)
}

func (s *UserServer) UpgradePassword(ctx context.Context, in *user.UpgradePasswordRequest) (*user.UpgradePasswordResponse, error) {
	l := userlogic.NewUpgradePasswordLogic(ctx, s.svcCtx)
	return l.UpgradePassword(in)
}

func (s *UserServer) AdminUserList(ctx context.Context, in *user.AdminUserListRequest) (*user.AdminUserListResponse, error) {
	l := userlogic.NewAdminUserListLogic(ctx, s.svcCtx)
	return l.AdminUserList(in)
}
